name: Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python version used for the build "
        required: false
        default: "3.12"
        type: string
      upload_artifacts:
        description: "Uploads wheel as a workflow artifact"
        required: false
        default: false
        type: boolean
      uv_version:
        description: "uv version to install in the DevContainer (e.g. 0.10.9)"
        required: false
        default: "0.10.9"
        type: string


jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      python_version: ${{ inputs.python_version }}
      upload_artifacts: ${{ inputs.upload_artifacts }}
      uv_version: ${{ inputs.uv_version }}
