name: Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: "Uploads wheel as a workflow artifact"
        required: false
        default: false
        type: boolean
      uv_version:
        description: "uv version to install in the DevContainer (e.g. 0.10.9)"
        required: false
        default: "0.10.9"
        type: string


jobs:
  parse-version:
    runs-on: ubuntu-latest
    outputs:
      depsight_version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: version
        run: |
          version=$(grep '^version' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> "$GITHUB_OUTPUT"

  call-build:
    needs: parse-version
    uses: ./.github/workflows/build.yml
    with:
      depsight_version: ${{ needs.parse-version.outputs.depsight_version }}
      upload_artifacts: ${{ inputs.upload_artifacts }}
      uv_version: ${{ inputs.uv_version }}
