name: On Release

on:
  release:
    types: [published]

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}
      upload_artifacts: true
